#!/bin/bash

PKGDIR="${FPKG_ROOT}/pkg"

if [ $# -ne 1 ]
then
    echo "Did not specify exactly one argument"
    exit 1
fi

pkg_version=$(qpkg "$1")
if [ $? -ne 0 ]
then
    echo $pkg_version
    exit 1
fi

zstd -qcd "$PKGDIR/$1-$pkg_version.tar.zst" | tar tf -
